Odiseo\SyliusBannerPlugin\Entity\BannerTranslation:
    properties:
        imageFile:
            - NotBlank:
                message: 'odiseo_sylius_banner_plugin.banner_translation.image_file.not_blank'
                groups: ['odiseo_image_create']
        mobileImageFile:
            - NotBlank:
                message: 'odiseo_sylius_banner_plugin.banner_translation.image_file.not_blank'
                groups: ['odiseo_image_create']
